version: '3.2'
services:
  frontend:
    build:
      context: ./frontend
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200" 
    volumes:
      - type: bind
        source: ./frontend/webapp
        target: /usr/local/webapp
  backend:
    build:
      context: ./backend
    command: addressbook-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis
